name: "Prevent Maven Artifact Overwrites"
description: "Prevent overwriting Maven artifacts from feature branches."

branding:
  icon: 'package'
  color: 'blue'

inputs:
  commit-message-suffix:
    description: "Text to add to the end of commit messages."
    default: ""
    required: false
    type: string
  enforce-branch-version:
    required: true
    type: boolean
  git-user-name:
    description: "GIT user name (to commit changes)"
    default: "github-actions[bot]"
    required: false
    type: string
  git-user-email:
    description: "GIT user email (to commit changes)"
    default: "github-actions[bot]@users.noreply.github.com"
    required: false
    type: string
  maven-args:
    description: "Additional arguments to pass to Maven commands"
    default: ""
    required: false
    type: string
  pom-file:
    description: "Maven POM file"
    default: "pom.xml"
    required: false
    type: string
  push-changes:
    required: true
    type: boolean

outputs:
  changes-made:
    description: "Whether this action modified any files"
    value: ${{ steps.run-script.outputs.changes-made }}

runs:
  using: "composite"
  steps:
    - name: Prevent Maven Artifact Overwrites
      id: run-script
      shell: bash
      env:
        BRANCH_NAME: ${{ github.ref_name }}
        ENFORCE_BRANCH_VERSION: ${{ inputs.enforce-branch-version }}
        PUSH_CHANGES: ${{ inputs.push-changes }}
        POM_FILE: ${{ inputs.pom-file }}
        MAVEN_ARGS: ${{ inputs.maven-args }}
        COMMIT_MESSAGE_SUFFIX: ${{ inputs.commit-message-suffix }}
        GIT_USER_NAME: ${{ inputs.git-user-name }}
        GIT_USER_EMAIL: ${{ inputs.git-user-email }}
      run: |
        chmod +x "${{ github.action_path }}/prevent-overwrites.sh"
        "${{ github.action_path }}/prevent-overwrites.sh"
